### ISSUE TITLE
Expanding the possibility of having more LP

### ISSUE THREAD

**Issue by psolite** [ParclFinance/v3-sdk-ts#2]
I am currently providing LP on Parcl, but I think partnering with Solana Banks like Marginfi, Drift and Kamino, can give the project an edge.

I this bull run must people will not be willing to provide LP because is on stable, when the market is having an up trend.

I understand the fact that people can lend and borrow USDC from these banks, but cutting out that extra step will go a long way for the project, with an article of risk involved to let people know what they are getting into with fine.

If the project needs assistance thinking on methods to manage risk I can help. Good luck.

**Comment by krishnaagrawal7508** [comment]
How can someone provide liquidation, there is no clear path for it...
