### ISSUE TITLE
moidfyPosition.ts not working

### ISSUE THREAD

**Issue by akasimo** [ParclFinance/v3-sdk-ts#4]
moidfyPosition.ts in the example folder is not working. 
I am using a wallet that I am already using in web ui. I just commented out deposit sections and added nothing.

I get the below responses from simulation. NO changes in the script but I the resposne 1 sometimes and get response 2 on other times:

resp 1:
{
  accounts: null,
  err: { InstructionError: [ 0, [Object] ] },
  logs: [
    'Program 3parcLrT7WnXAcyPfkCz49oofuuf2guUKkjuFkAhZW8Y invoke [1]',
    'Program log: Instruction: ModifyPosition',
    'Program log: Error: "Market not found in account map" (market_id=7) thrown at programs/parcl_v3/src/state/margin_account.rs:254',
    'Program log: AnchorError occurred. Error Code: MarketNotFoundInAccountMap. Error Number: 6107. Error Message: Market not found in account map.',
    'Program 3parcLrT7WnXAcyPfkCz49oofuuf2guUKkjuFkAhZW8Y consumed 18365 of 200000 compute units',
    'Program 3parcLrT7WnXAcyPfkCz49oofuuf2guUKkjuFkAhZW8Y failed: custom program error: 0x17db'
  ],
  returnData: null,
  unitsConsumed: 0
}

resp 2:
{
  accounts: null,
  err: { InstructionError: [ 0, [Object] ] },
  logs: [
    'Program 3parcLrT7WnXAcyPfkCz49oofuuf2guUKkjuFkAhZW8Y invoke [1]',
    'Program log: Instruction: ModifyPosition',
    'Program log: AnchorError occurred. Error Code: IntegerOverflow. Error Number: 6000. Error Message: Integer overflow.',
    'Program 3parcLrT7WnXAcyPfkCz49oofuuf2guUKkjuFkAhZW8Y consumed 13691 of 200000 compute units',
    'Program 3parcLrT7WnXAcyPfkCz49oofuuf2guUKkjuFkAhZW8Y failed: custom program error: 0x1770'
  ],
  returnData: null,
  unitsConsumed: 0
}

**Comment by cyotani** [comment]
Hi, adding on to this issue. I'm experiencing a similar thing. It appears that the modifyPosition.ts works fine when there are not active trades, or the market I'm attempting to modify is the ONLY positions I have open.

As soon as I try to open or modify a second market I get "Market not found in account map" error. 

If i close the all open positions, then I can once again open a new postiion.

Can you advise what I need to change in the "modifyPosition.ts" example to get it work work with more than one position?


![image](https://github.com/user-attachments/assets/f5e8c66d-46e3-4f2e-a16b-da36e5b795af)
